<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

    <head>

        <title>SanalPos Sistemi</title>

     	<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

        <meta http-equiv="PRAGMA" content="NO-CACHE" />

		<!-- Required Libraries -->
            <link href="ext/css/ext-all.css" rel="stylesheet" />
            <link rel="stylesheet" type="text/css" href="ext/css/fileuploadfield.css"/>
			
            <script src="ext/ext-base.js" type="text/javascript"></script>
            <script src="ext/ext-all.js" type="text/javascript"></script>
            <script src="ext/ux/form/Datetime.js" type="text/javascript"></script>
            <script src="ext/InputTextMask.js" type="text/javascript"></script>
            <script src="ext/ux/form/Combobox.js" type="text/javascript"></script>
            <script src="ext/ux/grid/Ext.ux.grid.Search.js?v=0.002" type="text/javascript"></script>
            <script src="ext/RowExpander.js" type="text/javascript"></script>
			<script src="ApplicationJS/MusteriApi.js?v=0.012" type="text/javascript"></script>
			<script src="ApplicationJS/Il-Ilce.js?v=0.03" type="text/javascript"></script>
			<script src="ApplicationJS/InputTextMask.js?v=0.01" type="text/javascript"></script>	
            <script src="ext/Util.js" type="text/javascript"></script>
            <script type="text/javascript" src="ext/ux/form/FileUploadField.js"></script>
	        <script src="ext/DynaCombo.js?v=0.001" type="text/javascript"></script>	
			<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    </head>
    <body>

<?php

            if (file_exists($applicationBodyFile)) {

                require_once($applicationBodyFile);

                echo "\n";

            } else {

                echo "dosya yok:" . $applicationBodyFile;

            }

?>	

    </body>

</html>